# Generated by Django 2.2.12 on 2021-02-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='姓名')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('avatar', models.ImageField(null=True, upload_to='avatar', verbose_name='头像')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('phone', models.CharField(default='', max_length=11)),
                ('vip', models.BooleanField(default=False, verbose_name='会员状态')),
                ('problem', models.CharField(max_length=90, verbose_name='问题')),
                ('key', models.CharField(max_length=50, verbose_name='答案')),
            ],
        ),
    ]
