# Generated by Django 2.2.12 on 2021-02-26 07:56

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default=login.models.default_sign, max_length=150, verbose_name='头像'),
        ),
    ]
